config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :line_items do
    get 'decrease', on: :member
    get 'increase', on: :member
  end

  resources :orders

  resources :carts

  resources :charges

  root to: 'course#index'

  get 'courses/:id', to: 'course#show', as: :course_item

  get '/courses/search/:q', to: 'course#search', as: :search

  get 'about', to: 'static_pages#about', as: :about

  get 'contact', to: 'static_pages#contact', as: :contact

  get 'ec', to: 'static_pages#school', as: :ec

  get 'ilac', to: 'static_pages#ilac', as: :ilac

  get 'new', to: 'static_pages#new', as: :new

  get 'sale', to: 'static_pages#sale', as: :sale

  # get 'schools/:id', to: 'static_pages#school', as: :school_item

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'application#hello'
end

app/models/order.rb
class Order < ApplicationRecord
  # validates :address, :email, presence: true
  has_many :line_items, dependent: :destroy
  belongs_to :user
  belongs_to :status

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  include CurrentCart
  before_action :set_cart, only: [:new, :create]
  before_action :ensure_cart_isnt_empty, only: :new
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show; end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit; end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    if user_signed_in?
      @order.user_id = current_user.id
      @order.pst_rate = current_user.province.pst
      @order.gst = current_user.province.gst
      @order.hst = current_user.province.hst
      @order.total = @cart.total_price
      @order.grand_total = @cart.grand_total(@cart.total_price, current_user)
      @order.status_id = 1
    end

    respond_to do |format|
      if @order.save
        #
        session[:total] = @cart.total_price

        if user_signed_in?
          session[:grand_total] = @cart.grand_total(@cart.total_price, current_user)
        end
        #
        format.html { redirect_to new_charge_url, notice: 'Pay with your Credit Card' }
        # format.html { redirect_to root_url, notice: 'Thank you for your order.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        #
        session[:total] = @cart.total_price
        #
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:email)
  end

  def ensure_cart_isnt_empty
    if @cart.line_items.empty?
      redirect_to root_url, notice: 'Your cart is empty'
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.slim
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      .container
        h2 = "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
        ul
          - @order.errors.full_messages.each do |message|
            li = message
            
  - if user_signed_in?        
    .container
      .row
        .col-12.field
          h5 = "Please enter your email and make sure that the information is correct, if not update it"
        .col-8.field
          = f.label :email
          = f.text_field :email, size: 20
        .col-8.field
          = current_user.first_name.capitalize
        .col-8.field
          = current_user.last_name.capitalize
        .col-8.field
          = current_user.address
        .col-8.field
          = current_user.city
        .col-8.field
          = current_user.province.name
        .col-8.field
          = current_user.postal_code
        .col-5.actions = f.submit 'Proceed to Payment'
  - else
    .container
      .row
        .col-8.field
          = f.label :address
          = f.text_area :address, rows: 2, cols: 39
        .col-8.field
          = f.label :email
          = f.text_field :email, size: 40
        .col-5.actions = f.submit 'Proceed to Payment2'

app/views/orders/edit.html.slim
h1 Editing order

== render 'form'

= link_to 'Show', @order
'  |
= link_to 'Back', orders_path

app/views/orders/index.html.slim
h1 Listing orders

table
  thead
    tr
      th Name
      th Address
      th Email
      th
      th
      th

  tbody
    - @orders.each do |order|
      tr
        td = order.name
        td = order.address
        td = order.email
        td = link_to 'Show', order
        td = link_to 'Edit', edit_order_path(order)
        td = link_to 'Destroy', order, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Order', new_order_path

app/views/orders/new.html.slim
.depot_form
  fieldset
    legend
      | Please Enter Your Details
    = render 'form', order: @order

app/views/orders/show.html.slim
p#notice = notice

p
  strong Name:
  = @order.name
p
  strong Address:
  = @order.address
p
  strong Email:
  = @order.email

= link_to 'Edit', edit_order_path(@order)
'  |
= link_to 'Back', orders_path