config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :line_items do
    get 'decrease', on: :member
    get 'increase', on: :member
  end

  resources :orders

  resources :carts

  resources :charges

  root to: 'course#index'

  get 'courses/:id', to: 'course#show', as: :course_item

  get '/courses/search/:q', to: 'course#search', as: :search

  get 'about', to: 'static_pages#about', as: :about

  get 'contact', to: 'static_pages#contact', as: :contact

  get 'ec', to: 'static_pages#school', as: :ec

  get 'ilac', to: 'static_pages#ilac', as: :ilac

  get 'new', to: 'static_pages#new', as: :new

  get 'sale', to: 'static_pages#sale', as: :sale

  # get 'schools/:id', to: 'static_pages#school', as: :school_item

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'application#hello'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(english_course_id: product.id)
    if current_item
      current_item.quantity += 1

    else
      current_item = line_items.build(english_course_id: product.id)
    end
    current_item
  end

  def remove_product(product)
    current_item = line_items.find_by(english_course_id: product.id)
    if current_item.quantity > 1
      current_item.quantity -= 1
    elsif current_item.quantity == 1
      current_item.destroy
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def grand_total(total, current_user)
    gst_rate = current_user.province.gst
    pst_rate = current_user.province.pst
    hst_rate = current_user.province.hst

    pst = (total * pst_rate).round(2)
    gst = (total * gst_rate).round(2)
    hst = (total * hst_rate).round(2)

    total + pst + gst + hst
  end

  def total_qty
    line_items.to_a.sum { |item| item.quantity }
  end

  def qty
    qty = 0
    @cart.line_items.each do |li|
      qty += li.quantity
    end
    qty
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show; end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit; end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.fetch(:cart, {})
  end

  # Handle invalide cart id
  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_url, notice: 'Invalid cart'
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.slim
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      h2 = "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      ul
        - @cart.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/carts/edit.html.slim
h1 Editing cart

== render 'form'

= link_to 'Show', @cart
'  |
= link_to 'Back', carts_path

app/views/carts/index.html.slim
h1 Listing carts

table
  thead
    tr
      th
      th
      th

  tbody
    - @carts.each do |cart|
      tr
        td = link_to 'Show', cart
        td = link_to 'Edit', edit_cart_path(cart)
        td = link_to 'Destroy', cart, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.slim
h1 New cart

== render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.erb
<% if user_signed_in? %>
<h2><%= current_user.first_name.capitalize %>'s Cart  </h2>
<% else %>
<h2> Your Cart </h2>
<% end %>

 <table>
  <% @cart.line_items.each do |item| %>
   <tr>
     <td><%= item.quantity %>&times;</td>
     <td><%= item.english_course.name %></td>
     <td class="item_price"><%= number_to_currency(item.total_price) %></td>
     <td><%= link_to "-", decrease_line_item_path(english_course_id: item.english_course), class:"btn btn-danger" %></td>
     <td><%= link_to "+", increase_line_item_path(english_course_id: item.english_course), class:"btn btn-success" %></td>
   </tr>
  <% end %>

  <% session[:qty] = @cart.total_qty %>
  
   <tr class="total_line">
     <td colspan="2">Total</td>
     <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
   </tr>

   <% if user_signed_in? %>

     <% if current_user.province.gst > 0 %>
     <tr>
       <td >GST</td>
       <td><%= current_user.province.gst %>%</td>
       <td><%= number_to_currency(current_user.province.gst * @cart.total_price) %></td>
     </tr>
     <% end %>

     <% if current_user.province.pst > 0 %>
     <tr>
       <td>PST</td>
       <td><%= current_user.province.pst %>%</td>
       <td><%= number_to_currency(current_user.province.pst * @cart.total_price) %></td>
     </tr>
     <% end %>

     <% if current_user.province.hst > 0 %>
     <tr>
       <td>HST</td>
       <td><%= current_user.province.hst %>%</td>
       <td><%= number_to_currency(current_user.province.hst * @cart.total_price) %></td>
     </tr>
     <% end %>

     <tr class="total_line">
       <td colspan="2">Grand Total</td>
       <td class="total_cell"><%= number_to_currency(@cart.grand_total(@cart.total_price,current_user)) %></td>
     </tr>

   <% end %>

 </table>
 <%= button_to "Checkout", new_order_path, method: :get, class:"btn btn-primary btn-sm" %>
 <%= button_to 'Empty cart', @cart, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %>