config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :line_items do
    get 'decrease', on: :member
    get 'increase', on: :member
  end

  resources :orders

  resources :carts

  resources :charges

  root to: 'course#index'

  get 'courses/:id', to: 'course#show', as: :course_item

  get '/courses/search/:q', to: 'course#search', as: :search

  get 'about', to: 'static_pages#about', as: :about

  get 'contact', to: 'static_pages#contact', as: :contact

  get 'ec', to: 'static_pages#school', as: :ec

  get 'ilac', to: 'static_pages#ilac', as: :ilac

  get 'new', to: 'static_pages#new', as: :new

  get 'sale', to: 'static_pages#sale', as: :sale

  # get 'schools/:id', to: 'static_pages#school', as: :school_item

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'application#hello'
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :english_course
  belongs_to :cart

  def total_price
    english_course.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < InheritedResources::Base
  include CurrentCart
  # before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:create, :decrease, :increase]

  def index
    @line_items = LineItem.all
  end

  def create
    # current_user = User.find[current_user.id]
    product = EnglishCourse.find(params[:english_course_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        # format.html { redirect_to @line_item.cart, notice: 'Line item was successfully created.' }
        format.html { redirect_to @line_item.cart }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def decrease
    product = EnglishCourse.find(params[:english_course_id])
    @line_item = @cart.remove_product(product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to cart_path, notice: 'Line item was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def increase
    product = EnglishCourse.find(params[:english_course_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to :back, notice: 'Line item was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  def line_item_params
    params.require(:line_item).permit(:english_course_id, :cart_id, :quantity)
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.slim
= form_for @line_item do |f|
  - if @line_item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@line_item.errors.count, "error")} prohibited this line_item from being saved:"
      ul
        - @line_item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :english_course
    = f.text_field :english_course
  .field
    = f.label :cart
    = f.text_field :cart
  .actions = f.submit

app/views/line_items/edit.html.slim
h1 Editing line_item

== render 'form'

= link_to 'Show', @line_item
'  |
= link_to 'Back', line_items_path

app/views/line_items/index.html.slim
h1 Listing line_items

table
  thead
    tr
      th English course
      th Cart
      th
      th
      th

  tbody
    - @line_items.each do |line_item|
      tr
        td = line_item.english_course
        td = line_item.cart
        td = link_to 'Show', line_item
        td = link_to 'Edit', edit_line_item_path(line_item)
        td = link_to 'Destroy', line_item, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.slim
h1 New line_item

== render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.slim
p#notice = notice

p
  strong English course:
  = @line_item.english_course
p
  strong Cart:
  = @line_item.cart

= link_to 'Edit', edit_line_item_path(@line_item)
'  |
= link_to 'Back', line_items_path