config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :line_items do
    get 'decrease', on: :member
    get 'increase', on: :member
  end

  resources :orders

  resources :carts

  resources :charges

  root to: 'course#index'

  get 'courses/:id', to: 'course#show', as: :course_item

  get '/courses/search/:q', to: 'course#search', as: :search

  get 'about', to: 'static_pages#about', as: :about

  get 'contact', to: 'static_pages#contact', as: :contact

  get 'ec', to: 'static_pages#school', as: :ec

  get 'ilac', to: 'static_pages#ilac', as: :ilac

  get 'new', to: 'static_pages#new', as: :new

  get 'sale', to: 'static_pages#sale', as: :sale

  # get 'schools/:id', to: 'static_pages#school', as: :school_item

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'application#hello'
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(english_course_id: product.id)
    if current_item
      current_item.quantity += 1

    else
      current_item = line_items.build(english_course_id: product.id)
    end
    current_item
  end

  def remove_product(product)
    current_item = line_items.find_by(english_course_id: product.id)
    if current_item.quantity > 1
      current_item.quantity -= 1
    elsif current_item.quantity == 1
      current_item.destroy
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def grand_total(total, current_user)
    gst_rate = current_user.province.gst
    pst_rate = current_user.province.pst
    hst_rate = current_user.province.hst

    pst = (total * pst_rate).round(2)
    gst = (total * gst_rate).round(2)
    hst = (total * hst_rate).round(2)

    total + pst + gst + hst
  end

  def total_qty
    line_items.to_a.sum { |item| item.quantity }
  end

  def qty
    qty = 0
    @cart.line_items.each do |li|
      qty += li.quantity
    end
    qty
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/english_course.rb
class EnglishCourse < ApplicationRecord
  belongs_to :school
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  #
  searchkick
  def search_data
    {
      name: name,
      description: description,
      school_id: school_id
    }
  end
  #
  mount_uploader :image, ImageUploader
  #
  validates :name, presence: true
  validates :name, length: { minimum: 5 }
  validates :name, length: { maximum: 50 }
  validates :description, presence: true
  validates :description, length: { minimum: 20 }
  validates :description, length: { maximum: 500 }
  validates :price, presence: true
  validates :price, numericality: true
  validates :image, presence: true

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :english_course
  belongs_to :cart

  def total_price
    english_course.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  # validates :address, :email, presence: true
  has_many :line_items, dependent: :destroy
  belongs_to :user
  belongs_to :status

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
end

app/models/school.rb
class School < ApplicationRecord
  has_many :english_courses
  validates :name, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :orders
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  belongs_to :province
  has_many :orders, dependent: :destroy
  # does not work
  # devise :database_authenticatable, :validatable, password_length: 1..128

  def name
    first_name + ' ' + last_name
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show; end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit; end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.fetch(:cart, {})
  end

  # Handle invalide cart id
  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_url, notice: 'Invalid cart'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Aclick3</title>
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, :class => "nav-link" %> <span class="sr-only">(current)</span>
          </li>

          <li class="nav-item">
            <%= link_to "About", about_path, :class => "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Contact", contact_path, :class => "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "New", new_path, :class => "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sale", sale_path, :class => "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Schools
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "EC", ec_path, :class => "dropdown-item" %>
              <%= link_to "ILAC", ilac_path, :class => "dropdown-item" %>
            </div>
          </li>
        </ul>

        <!-- <%= form_tag root_path, method: :get do %>
          <%= text_field_tag :q, nil, placeholder: "Search" %>
        <% end %> -->

        <%= form_tag root_path, method: :get do %>
          <%= text_field_tag :q, nil, placeholder: "Search" %>
          <%= check_box_tag 'enable', :class => "nav-link" %>
          <%= select_tag :school_id, options_from_collection_for_select(School.all, :id, :name), {:disabled => true} %>
        <% end %>

        <ul class="navbar-nav mr-auto">

          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to current_user.first_name.capitalize, edit_user_registration_path, :class => "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "nav-link" %>
            </li>

            <% cart_id = session[:cart_id] %>
            <% qty = session[:qty] %>
            <% if cart_id!=nil %>
              <li class="nav-item"><%= link_to cart_path(cart_id), :class => "nav-link"  do %>
                <span class="fa fa-shopping-cart"><span> Cart (<%= pluralize(qty, "item") %>) <% end %>
              </li>
            <% end %>

          <% else %>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, :class => "nav-link" %>
            </li>

            <li class="nav-item">
            <span class="nav-link"> | </span>
            </li>

            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, :class => "nav-link" %>
            </li>
        <% end %>

        </ul>
      </div>
    </nav>


    <% if notice %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= notice %>
        </div>
    <% end %>

    <% if alert %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= alert %>
        </div>
    <% end %>

    <div id="wrap">
      <div class="container">
          <%= yield %>
      </div>
    </div>

    <div id="footer">
     <div class="container">
       <p class="text-muted">Footer @2017</p>
     </div>
   </div>

   <script>
   $(function () {
     var $checkbox = $('[id^="enable"]'),
         $select = $('#school_id');

     $checkbox.change(function (e) {
         $select.prop('disabled', !$checkbox.is(':checked'))
     });
   });
   </script>

  </body>

</html>